# Generated by Django 2.2.7 on 2019-12-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_hotel_hotelurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelid',
            field=models.IntegerField(default=1),
        ),
    ]
