# Generated by Django 2.2.7 on 2019-12-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_hotel_hotelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotelid',
            field=models.IntegerField(blank=True),
        ),
    ]
