# Generated by Django 2.2.7 on 2019-12-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191210_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelurl',
            field=models.URLField(blank=True),
        ),
    ]
