# Generated by Django 2.2.7 on 2019-12-10 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_hotel_hotelurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotelid',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
