# Generated by Django 2.2.7 on 2019-12-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20191210_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelid',
            new_name='hotelprice',
        ),
        migrations.AddField(
            model_name='hotel',
            name='twosites',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='womanonly',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelname',
            field=models.CharField(max_length=40),
        ),
    ]
